### ISSUE TITLE
SalmonTE* snakemake error FileNotFoundError: [Errno 2] No such file or directory: 'salmonQuant/EXPR.csv'

### ISSUE THREAD

**Issue by Mjaraespejo** [Hoffmann-Lab/TEdetectionEvaluation#7]
Hello, i tried to run SalmonTE* both on example data and on my own data, and the tool is failing.
This is the terminal output:
SalmonTE.py quant --reference=phaw_TE-instances --outpath=salmonQuant  --exprtype=count /drives/raid/AboobakerLab/data/rna_data/paired/embryo_s1s9/trim/S1_1_out_paired.fq /drives/raid/AboobakerLab/data/rna_data/paired/embryo_s1s9/trim/S1_2_out_paired.fq
2021-11-12 15:24:50,404 Starting quantification mode
2021-11-12 15:24:50,404 Collecting FASTQ files...
2021-11-12 15:24:50,405 The input dataset is considered as a paired-ends dataset.
2021-11-12 15:24:50,405 Collected 1 FASTQ files.
2021-11-12 15:24:50,405 Quantification has been finished.
2021-11-12 15:24:50,405 Running Salmon using Snakemake
NameError in line 24 of /drives/raid/AboobakerLab/software/SalmonTE/snakemake/Snakefile.paired:
name 'directory' is not defined
  File "/drives/raid/AboobakerLab/software/SalmonTE/snakemake/Snakefile.paired", line 24, in <module>
2021-11-12 15:24:50,518 NameError in line 24 of /drives/raid/AboobakerLab/software/SalmonTE/snakemake/Snakefile.paired:
name 'directory' is not defined
  File "/drives/raid/AboobakerLab/software/SalmonTE/snakemake/Snakefile.paired", line 24, in <module>
Traceback (most recent call last):
  File "/drives/raid/AboobakerLab/software/SalmonTE/SalmonTE.py", line 292, in <module>
    run(args)
  File "/drives/raid/AboobakerLab/software/SalmonTE/SalmonTE.py", line 243, in run
    run_salmon(param)
  File "/drives/raid/AboobakerLab/software/SalmonTE/SalmonTE.py", line 156, in run_salmon
    with open(os.path.join(param["--outpath"], "EXPR.csv" ), "r") as inp:
FileNotFoundError: [Errno 2] No such file or directory: 'salmonQuant/EXPR.csv'

I run the analysis using python 3.6 and snakemake 5.1.5

This issue was reported previously here: https://github.com/hyunhwan-jeong/SalmonTE/issues/14 for SalmonTE, so I upgraded snakemake to version 5.2 , which solved the issue previously, but now I get this terminal output:

SalmonTE.py quant --reference=phaw_TE-instances --outpath=salmonQuant  --exprtype=count /drives/raid/AboobakerLab/data/rna_data/paired/embryo_s1s9/trim/S1_1_out_paired.fq /drives/raid/AboobakerLab/data/rna_data/paired/embryo_s1s9/trim/S1_2_out_paired.fq
2021-11-12 15:50:16,052 Starting quantification mode
2021-11-12 15:50:16,053 Collecting FASTQ files...
2021-11-12 15:50:16,053 The input dataset is considered as a paired-ends dataset.
2021-11-12 15:50:16,053 Collected 1 FASTQ files.
2021-11-12 15:50:16,053 Quantification has been finished.
2021-11-12 15:50:16,053 Running Salmon using Snakemake
Building DAG of jobs...
2021-11-12 15:50:16,146 Building DAG of jobs...
Using shell: /usr/bin/bash
2021-11-12 15:50:16,157 Using shell: /usr/bin/bash
Job counts:
        count   jobs
        1       all
        1       collect_abundance
        1       collect_mappability
        1       run_salmon_fq
        4
2021-11-12 15:50:16,158 Job counts:
        count   jobs
        1       all
        1       collect_abundance
        1       collect_mappability
        1       run_salmon_fq
        4
    Error in rule run_salmon_fq:
2021-11-12 15:50:16,396     Error in rule run_salmon_fq:
        jobid: 3
2021-11-12 15:50:16,397         jobid: 3
        output: salmonQuant/S1_1_out
2021-11-12 15:50:16,397         output: salmonQuant/S1_1_out

2021-11-12 15:50:16,397 
RuleException:
CalledProcessError in line 27 of /drives/raid/AboobakerLab/software/SalmonTE/snakemake/Snakefile.paired:
Command ' set -euo pipefail;  /drives/raid/AboobakerLab/software/SalmonTE/salmon/linux/bin/salmon quant -q -i /drives/raid/AboobakerLab/software/SalmonTE/reference/phaw_TE-instances -l A -1 /tmp/tmpl2xykfb3/S1_1_out_R1.fastq -2 /tmp/tmpl2xykfb3/S1_1_out_R2.fastq -o salmonQuant/S1_1_out -p 4 2>/dev/null ' returned non-zero exit status 1.
  File "/drives/raid/AboobakerLab/software/SalmonTE/snakemake/Snakefile.paired", line 27, in __rule_run_salmon_fq
  File "/drives/ssd1/manuel/miniconda3/envs/py3.6/lib/python3.6/concurrent/futures/thread.py", line 56, in run
2021-11-12 15:50:16,397 RuleException:
CalledProcessError in line 27 of /drives/raid/AboobakerLab/software/SalmonTE/snakemake/Snakefile.paired:
Command ' set -euo pipefail;  /drives/raid/AboobakerLab/software/SalmonTE/salmon/linux/bin/salmon quant -q -i /drives/raid/AboobakerLab/software/SalmonTE/reference/phaw_TE-instances -l A -1 /tmp/tmpl2xykfb3/S1_1_out_R1.fastq -2 /tmp/tmpl2xykfb3/S1_1_out_R2.fastq -o salmonQuant/S1_1_out -p 4 2>/dev/null ' returned non-zero exit status 1.
  File "/drives/raid/AboobakerLab/software/SalmonTE/snakemake/Snakefile.paired", line 27, in __rule_run_salmon_fq
  File "/drives/ssd1/manuel/miniconda3/envs/py3.6/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job run_salmon_fq since they might be corrupted:
salmonQuant/S1_1_out
2021-11-12 15:50:16,398 Removing output files of failed job run_salmon_fq since they might be corrupted:
salmonQuant/S1_1_out
Shutting down, this might take some time.
2021-11-12 15:50:16,399 Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
2021-11-12 15:50:16,399 Exiting because a job execution failed. Look above for error message
Complete log: /drives/ssd1/manuel/phaw/2021_analysis/repeats_phaw/expression_analysis/TE_ExpbyInstance/.snakemake/log/2021-11-12T155016.123800.snakemake.log
2021-11-12 15:50:16,399 Complete log: /drives/ssd1/manuel/phaw/2021_analysis/repeats_phaw/expression_analysis/TE_ExpbyInstance/.snakemake/log/2021-11-12T155016.123800.snakemake.log
Traceback (most recent call last):
  File "/drives/raid/AboobakerLab/software/SalmonTE/SalmonTE.py", line 292, in <module>
    run(args)
  File "/drives/raid/AboobakerLab/software/SalmonTE/SalmonTE.py", line 243, in run
    run_salmon(param)
  File "/drives/raid/AboobakerLab/software/SalmonTE/SalmonTE.py", line 156, in run_salmon
    with open(os.path.join(param["--outpath"], "EXPR.csv" ), "r") as inp:
FileNotFoundError: [Errno 2] No such file or directory: 'salmonQuant/EXPR.csv'

I do not get any oupput files using either 5.1 or 5.2 snakemake.
Could you please help me? 
Which snakemake version you used to run the TE expression by instance using the SalmonTE*.py script?

Thank you

**Comment by roschwarz** [comment]
Hi Mjaraespejo,

I use the snakemake version 5.3.0. Is this already solving the problem? If not, please let me know.

Best,

Robert

**Comment by Mjaraespejo** [comment]
Hi Robert, I run the analysis using snakemake 5.3.0 and  I still have issues. The terminal output is:

2021-11-15 10:18:30,875 Starting quantification mode
2021-11-15 10:18:30,876 Collecting FASTQ files...
2021-11-15 10:18:31,099 The input dataset is considered as a paired-ends dataset.
2021-11-15 10:18:31,099 Collected 1 FASTQ files.
2021-11-15 10:18:31,100 Quantification has been finished.
2021-11-15 10:18:31,100 Running Salmon using Snakemake
Job counts:
        count   jobs
        1       all
        1       collect_abundance
        1       collect_mappability
        1       run_salmon_fq
        4
2021-11-15 10:18:31,214 Job counts:
        count   jobs
        1       all
        1       collect_abundance
        1       collect_mappability
        1       run_salmon_fq
        4
[Mon Nov 15 10:18:31 2021]
2021-11-15 10:18:31,450 [Mon Nov 15 10:18:31 2021]
Error in rule run_salmon_fq:
2021-11-15 10:18:31,450 Error in rule run_salmon_fq:
    jobid: 3
2021-11-15 10:18:31,450     jobid: 3
    output: salmonQuant/S1_1_out
2021-11-15 10:18:31,450     output: salmonQuant/S1_1_out

2021-11-15 10:18:31,450 
RuleException:
CalledProcessError in line 27 of /drives/raid/AboobakerLab/software/SalmonTE/snakemake/Snakefile.paired:
Command ' set -euo pipefail;  /drives/raid/AboobakerLab/software/SalmonTE/salmon/linux/bin/salmon quant -q -i /drives/raid/AboobakerLab/software/SalmonTE/reference/phaw_TE-instances -l A -1 /tmp/tmpsd2a3ubz/S1_1_out_R1.fastq -2 /tmp/tmpsd2a3ubz/S1_1_out_R2.fastq -o salmonQuant/S1_1_out -p 4 2>/dev/null ' returned non-zero exit status 1.
  File "/drives/raid/AboobakerLab/software/SalmonTE/snakemake/Snakefile.paired", line 27, in __rule_run_salmon_fq
  File "/drives/ssd1/manuel/miniconda3/envs/py3.6/lib/python3.6/concurrent/futures/thread.py", line 56, in run
2021-11-15 10:18:31,451 RuleException:
CalledProcessError in line 27 of /drives/raid/AboobakerLab/software/SalmonTE/snakemake/Snakefile.paired:
Command ' set -euo pipefail;  /drives/raid/AboobakerLab/software/SalmonTE/salmon/linux/bin/salmon quant -q -i /drives/raid/AboobakerLab/software/SalmonTE/reference/phaw_TE-instances -l A -1 /tmp/tmpsd2a3ubz/S1_1_out_R1.fastq -2 /tmp/tmpsd2a3ubz/S1_1_out_R2.fastq -o salmonQuant/S1_1_out -p 4 2>/dev/null ' returned non-zero exit status 1.
  File "/drives/raid/AboobakerLab/software/SalmonTE/snakemake/Snakefile.paired", line 27, in __rule_run_salmon_fq
  File "/drives/ssd1/manuel/miniconda3/envs/py3.6/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Exiting because a job execution failed. Look above for error message
2021-11-15 10:18:31,453 Exiting because a job execution failed. Look above for error message
Traceback (most recent call last):
  File "/drives/raid/AboobakerLab/software/SalmonTE/SalmonTE.py", line 292, in <module>
    run(args)
  File "/drives/raid/AboobakerLab/software/SalmonTE/SalmonTE.py", line 243, in run
    run_salmon(param)
  File "/drives/raid/AboobakerLab/software/SalmonTE/SalmonTE.py", line 156, in run_salmon
    with open(os.path.join(param["--outpath"], "EXPR.csv" ), "r") as inp:
FileNotFoundError: [Errno 2] No such file or directory: 'salmonQuant/EXPR.csv'

**Comment by roschwarz** [comment]
Could it be that you don't have enough threads? 
SalmonTE.py uses by default 4 threads. You can reduce the number in the script SalmonTE.py on line 222 or you use the flag "--num_threads=1" when you call SalmonTE.py

Best
Robert

**Comment by Mjaraespejo** [comment]
I do not think so it's about thread availability. This are some of system features:
CPU(s):                          128
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       2

Currently, no processes are running on the server:
![server](https://user-images.githubusercontent.com/10467208/141776878-73362eae-2d0a-419e-9441-2347ae9a0e18.jpg)

**Comment by roschwarz** [comment]
Is the following command working?


` /drives/raid/AboobakerLab/software/SalmonTE/salmon/linux/bin/salmon quant -q -i /drives/raid/AboobakerLab/software/SalmonTE/reference/phaw_TE-instances -l A -1 /drives/raid/AboobakerLab/data/rna_data/paired/embryo_s1s9/trim/S1_1_out_paired.fq -2 /drives/raid/AboobakerLab/data/rna_data/paired/embryo_s1s9/trim/S1_2_out_paired.fq -o test -p 10`

**Comment by Mjaraespejo** [comment]
This is the ouput from the command you sent:

Version Info: ### PLEASE UPGRADE SALMON ###
### A newer version of salmon with important bug fixes and improvements is available. ####
###
The newest version, available at https://github.com/COMBINE-lab/salmon/releases
contains new features, improvements, and bug fixes; please upgrade at your
earliest convenience.
###
Sign up for the salmon mailing list to hear about new versions, features and updates at:
https://oceangenomics.com/subscribe
###
Exception : [rapidjson internal assertion failure: IsObject()]
/drives/raid/AboobakerLab/software/SalmonTE/salmon/linux/bin/salmon quant was invoked improperly.
For usage information, try /drives/raid/AboobakerLab/software/SalmonTE/salmon/linux/bin/salmon quant --help
Exiting.

**Comment by Mjaraespejo** [comment]
Hello,

Based on the error message: "Exception : [rapidjson internal assertion failure: IsObject()]", I think I found the issue. 
By mistake I was running the command using an index generated using Salmon, not SalmonTE.
I run the command youi sent me with usingthe index generated with SalmonTE and it is running perfectly!

**Comment by Mjaraespejo** [comment]
Hello,

Based on the error message: "Exception : [rapidjson internal assertion failure: IsObject()]", I think I found the issue.
By mistake I was running the command using an index generated using Salmon, not SalmonTE.
I run the command you sent me with using the index generated with SalmonTE and the the command run perfectly.

Thanks a lot!
